name: Lint diagnostics
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, flake8, pep257]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: rolling
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: rolling
        linter: ${{ matrix.linter }}
        package-name: turtle_tf2_py
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, cpplint, uncrustify]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: rolling
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: rolling
        linter: ${{ matrix.linter }}
        package-name: turtle_tf2_cpp
